name: Login to Dynamics 365

on:
  push:
  workflow_dispatch:

jobs:
  login:
    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest
    env:
      DATAVERSE_URL: ${{ secrets.DATAVERSE_URL }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ secrets.DATAVERSE_URL }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret:  ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}
