name: Login to Dynamics 365

on:
  push:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install Dataverse SDK
      run: dotnet add package Microsoft.PowerPlatform.Dataverse.Client

    - name: Login to Dynamics 365
      run: |
        echo "using Microsoft.PowerPlatform.Dataverse.Client;" > Program.cs
        echo "using System;" >> Program.cs
        echo "namespace YourNamespace" >> Program.cs
        echo "{" >> Program.cs
        echo "    class Program" >> Program.cs
        echo "    {" >> Program.cs
        echo "        static void Main(string[] args)" >> Program.cs
        echo "        {" >> Program.cs
        echo "            string url = Environment.GetEnvironmentVariable(\"DATAVERSE_URL\");" >> Program.cs
        echo "            string clientId = Environment.GetEnvironmentVariable(\"CLIENT_ID\");" >> Program.cs
        echo "            string clientSecret = Environment.GetEnvironmentVariable(\"CLIENT_SECRET\");" >> Program.cs
        echo "            string tenantId = Environment.GetEnvironmentVariable(\"TENANT_ID\");" >> Program.cs
        echo "            var connectionString = $"AuthType=ClientSecret;Url={url};ClientId={clientId};ClientSecret={clientSecret};Authority=https://login.microsoftonline.com/{tenantId}\";" >> Program.cs
        echo "            using (var serviceClient = new ServiceClient(connectionString))" >> Program.cs
        echo "            {" >> Program.cs
        echo "                if (serviceClient.IsReady)" >> Program.cs
        echo "                {" >> Program.cs
        echo "                    Console.WriteLine(\"Successfully logged in to Dynamics 365!\");" >> Program.cs
        echo "                }" >> Program.cs
        echo "                else" >> Program.cs
        echo "                {" >> Program.cs
        echo "                    Console.WriteLine(\"Failed to log in to Dynamics 365.\");" >> Program.cs
        echo "                }" >> Program.cs
        echo "            }" >> Program.cs
        echo "        }" >> Program.cs
        echo "    }" >> Program.cs
        echo "}" >> Program.cs
        dotnet run
      env:
        DATAVERSE_URL: ${{ secrets.DATAVERSE_URL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
